# CodeRabbit設定ファイル
# https://docs.coderabbit.ai/guides/configure-coderabbit

# レビュー言語を日本語に設定
language: ja-JP

# レビューの詳細度
reviews:
  # 高レベルの要約を有効化
  high_level_summary: true

  # 詳細なレビューコメント
  review_status: true

  # 詩的な要約（オプション：オフにすることも可能）
  poem: true

  # コードの品質チェック
  tools:
    # セキュリティ脆弱性チェック
    security: true

    # パフォーマンスの問題
    performance: true

    # ベストプラクティス
    best_practices: true

# 自動レビューの設定
auto_review:
  enabled: true

  # 特定のファイルを除外（必要に応じて調整）
  exclude:
    - "*.md"
    - "*.txt"
    - "package-lock.json"
    - "yarn.lock"
